# Generated by Django 4.1.3 on 2022-12-21 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_measurement_sensors_alter_measurement_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='sensors',
        ),
        migrations.AddField(
            model_name='measurement',
            name='id_sensors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='measurement.sensor'),
        ),
    ]
