# Generated by Django 4.1.3 on 2022-12-22 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_remove_measurement_sensors_measurement_id_sensors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='id_sensors',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor'),
        ),
    ]
